version: "3"

services:
  python_debian_{{UUID}}:
    image: ${CONTAINER_BASENAME}_image
    container_name: ${CONTAINER_BASENAME}_{{UUID}}
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        DEBIAN_DISTRIB: $DEBIAN_DISTRIB
        POETRY_VERSION: $POETRY_VERSION
    volumes:
      - ..:/workspaces:cached
      - $CACHE_FOLDER:/home/vscode/.cache
      - $DATA_FOLDER:/data
      - $HOME/.ssh/authorized_keys:/home/vscode/.ssh/authorized_keys
      - $HOME/.ssh/id_rsa:/home/vscode/.ssh/id_rsa
      - $HOME/.ssh/id_rsa.pub:/home/vscode/.ssh/id_rsa.pub
      - /dev/shm:/dev/shm
      - /sys:/sys
    ulimits:
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
